AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
  TargetRubyVersion: 2.3
Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Style/EmptyElse:
  EnforcedStyle: empty
Metrics/ParameterLists:
  CountKeywordArgs: false
