language: ruby
rvm:
  - "2.3.0"
services:
  - postgresql
before_script:
  - "psql -c 'create database confessions_test;' -U postgres"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
notifications:
  email: false
  slack:
    on_success: change
    secure: aCY+Qj2aOmT0ACgPYBFbHsDe7VsKgEzkRZRhcS+wYvubYWBhLlF0gTajFUyDH3tW357xnVE8EWFoLe7rPhhl1WCKCKyluDuAn86HjzrO4t9dPGjQLzhSpz+P5k/cVZbGjOeveO6wP8mzb3AgE9WROO/6M4RGiIiKXHmq7krBev3utQlAyG2K0hm3L93hCk8e/6pFXM07qLziuosZxnhxjj8qr9jXR6l24ic/R6h91wDPn7QJFffR5AJRxvGAf90XIyH4q18AtoAnaS7xQHhzZx2/3TT53wHL3wsgq7GUPzeQcFRwmMu+snwZU+Oz6NqahfE3WNa4LFjqsbgsDgOk5Pq9i6/8PxXUypjej0r6Spz4pfRp64LU0aGzlakxe7rE1lsR9Dz1h0jd36g9GS3h7qpKX59U7KT4U4VCet1EACbB9iExwawibVeDO0gnojMvHaeyc60jWawwsILoVgnZklU8NQpkLfCwchsp1zrWbNV+Msp4jS/527YP2W9E/Mw38z0b0vIwWKGA66OyYVXXSEKzxyJGqzz+ZOI35aMt0b2PUwxDHouLnbEOVSsTDHVTIVfxx7T0FTa6iV2jXuX4xEVNr0ziBzXr/LV+XiVy7r/V/fx2P9Oi2cOHWLaqL0L/RQlWPXhvGFfOurqFWPVB3Vms/L6VBgHzhpSznUFywzc=
script:
  - bundle exec rake
  - bundle exec rubocop
addons:
  postgresql: "9.4"
cache: bundler
